[metrics]
go_process = true

[api]
address = ":5002"

[postgres]
dsn = "postgres://postgres:postgres@127.0.0.1:5433/chain_data"

[jetstream]
endpoint = "nats://127.0.0.1:4222"
id = "inethi-indexer-1"

[chain]
rpc_endpoint = "http://127.0.0.1:8545"
chainid = 1337
vault_address = ""

[inethi]
endpoint = ""
api_key = ""

[notify]
endpoint = ""
bearer_token = ""
